backend:
  name: git-gateway
local_backend: true
# publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img"

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    delete: true
    extension: json
    format: json
    slug: "{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: Title }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
        }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

